/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 flower-draco.glb --transform 
Files: flower-draco.glb [546.08KB] > C:\Users\noahj\OneDrive\Documents\GitHub\wedding\wedding-site\public\flower-draco-transformed.glb [505.02KB] (8%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/flower-draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.539, 19.36, 0.044]} rotation={[-Math.PI / 2, 0, -2.627]} scale={100}>
        <mesh geometry={nodes.Petal_002_Petals2_0_1.geometry} material={materials.Petals2} />
        <mesh geometry={nodes.Petal_002_Petals2_0_2.geometry} material={materials.Petals1} />
        <mesh geometry={nodes.Petal_002_Petals2_0_3.geometry} material={materials.Petals3} />
        <mesh geometry={nodes.Petal_002_Petals2_0_4.geometry} material={materials.Petals4} />
        <mesh geometry={nodes.Petal_002_Petals2_0_5.geometry} material={materials.Petals5} />
        <mesh geometry={nodes.Petal_002_Petals2_0_6.geometry} material={materials.Petals6} />
        <mesh geometry={nodes.Petal_002_Petals2_0_7.geometry} material={materials.Petals7} />
        <mesh geometry={nodes.Petal_002_Petals2_0_8.geometry} material={materials.Petals8} />
        <mesh geometry={nodes.Petal_002_Petals2_0_9.geometry} material={materials.Petals9} />
        <mesh geometry={nodes.Petal_002_Petals2_0_10.geometry} material={materials.Petals10} />
        <mesh geometry={nodes.Petal_002_Petals2_0_11.geometry} material={materials.Petals11} />
        <mesh geometry={nodes.Petal_002_Petals2_0_12.geometry} material={materials.Petals12} />
        <mesh geometry={nodes.Petal_002_Petals2_0_13.geometry} material={materials.Petals14} />
      </group>
      <mesh geometry={nodes.Stems_Stems_0.geometry} material={materials.Stems} position={[-0.459, -4.503, 0.735]} rotation={[-Math.PI / 2, 0, -2.627]} scale={100} />
      <group position={[-0.769, 5.571, 1.131]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Leaves_001_Leaves1_0_1.geometry} material={materials.Leaves1} />
        <mesh geometry={nodes.Leaves_001_Leaves1_0_2.geometry} material={materials.Leaves6} />
      </group>
      <mesh geometry={nodes.Ribbons_001_Ribbons1_0.geometry} material={materials.Ribbons1} position={[0.379, -9.88, 0.971]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <group position={[-0.667, 5.969, 3.621]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.SmallPlants_001_SmallPlants3_0_1.geometry} material={materials.SmallPlants3} />
        <mesh geometry={nodes.SmallPlants_001_SmallPlants3_0_2.geometry} material={materials.SmallPlants1} />
        <mesh geometry={nodes.SmallPlants_001_SmallPlants3_0_3.geometry} material={materials.SmallPlants2} />
      </group>
    </group>
  )
}

useGLTF.preload('/flower-draco-transformed.glb')
